AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app
  
Globals:
  Function:
    Timeout: 3

Parameters:
  TableName:
    Type: String
    Default: 'Booking'
    Description: (Required) The name of the new DynamoDB table you want to create and save to. Minimum 3 characters
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z]+$
    ConstraintDescription: 'Required parameter. Must be characters only. No numbers allowed.'

Resources:
  BookingTrip:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.bookingTripHandler
      Runtime: nodejs12.x
      CodeUri: booking/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
      Events:
        CreateBooking:
          Type: Api
          Properties:
            Path: /booking
            Method: POST
        UpdateBooking:
          Type: Api
          Properties:
            Path: /booking/{bookingId}
            Method: ANY
  BookingTripTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: bookingId
          AttributeType: S
      KeySchema:
        - AttributeName: bookingId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BookingApi:
    Description: "API Gateway endpoint URL for Prod stage for Booking Trip function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/booking/"
  BookingTrip:
    Description: "Booking Trip Lambda Function ARN"
    Value: !GetAtt BookingTrip.Arn
  BookingTripIamRole:
    Description: "Implicit IAM Role created for Booking Trip function"
    Value: !GetAtt BookingTripRole.Arn
